config/routes.rb
Rails.application.routes.draw do

  get '/series', to: 'series#index', as: :series
  get '/series/new', to: 'series#new', as: :new_serie
  post '/series', to: 'series#create'
  get '/series/:id', to: 'series#show', as: :serie
  delete '/series/:id', to: 'series#destroy'
  post '/series/:series_id/reviews', to: 'reviews#create', as: :serie_reviews
  get '/series/:series_id/reviews/new', to: 'reviews#new', as: :new_series_review
  delete  '/reviews/:id', to: 'reviews#destroy', as: :review
  root to: 'series#index'
  # resources :series, path: :series
  # resources :series, except: :show do
  #   resources :reviews, only: [:new, :create]
  # end
  # resources :reviews, only: [:destroy]
  # get 'series/:id', to: 'series#show', as: :serie


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :serie
  validates :content, presence: true
end

app/models/serie.rb
class Serie < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :title, presence: true
  has_one_attached :photo
  validates :photo, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @serie = Serie.find(params[:series_id])
    @review = Review.new
  end

  def create
    @serie = Serie.find(params[:series_id])
    @review = Review.new(review_params)
    @review.serie = @serie
    if @review.save
      redirect_to serie_path(@serie)
    else
      render :new_series_review
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to serie_path(@review.serie)
  end

  private

  def review_params
    params.require(:review).permit(:content, :photo)
  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_serie, only: [:show, :edit, :update, :destroy ]
  def index
    @series = Serie.all
  end

  def show
    @reviews = @serie.reviews
  end

  def new
    @serie = Serie.new
  end

  def create
    @serie = Serie.new(serie_params)
    if @serie.save
      redirect_to serie_path(@serie), notice: "A new title was added!"
    else
      render :new
    end
  end

  def destroy
    @serie.destroy
    redirect_to series_path, notice: 'Title was destroyed'
  end

  private

  def set_serie
    @serie = Serie.find(params[:id])
  end

  def serie_params
    params.require(:serie).permit(:title, :rating, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TvSeries</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to 'Home', series_path, class: "btn btn-warning" %>
  <div id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Add a title", new_serie_path, class: "btn btn-warning" %>
      </li>
    </ul>
  </div>
</div>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reviews/new.html.erb
<div class="container">
  <h1>New Review for <%= @serie.title %></h1>
  <%= simple_form_for [@serie, @review] do |f| %>
    <%= f.input :content %>
    <%= f.submit class: 'btn btn-warning' %>
  <% end %>
    <%= link_to "back " , serie_path(@serie), class: 'btn btn-warning btn-sm my-2' %>
</div>

app/views/series/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<div class="body-container">
  <%#= link_to 'add new title', new_serie_path , class: 'btn btn-warning' %>
  <%#= simple_form_for :search, url: series_index_path, method: "GET", html: { class: 'form-inline' } do |f| %>
    <%#= f.input :name, input_html: {value: ""} %>
    <%#= f.submit "Search", class: "btn btn-primary" %>
    <%# end %>
    <div class="card-grid">
      <!-- <div class="card-series"> -->
      <% @series.each do |serie| %>
       <% if serie.photo.attached? %>
          <div class="card-category">
          <%=  cl_image_tag serie.photo.key, class: 'card-img', alt: "alttext" %>
            <%= link_to " " , serie_path(serie), class: 'card-link' %>
            <div class="card-body">
              <p class="card-text"><%= serie.title %></p>
              <p><%= serie.rating %> </p>
            </div>
          </div>
        <% else %>
         <div class="card-category">
            <%= image_tag serie.image, class: 'card-img', alt: "alttext" %>
            <%= link_to " " , serie_path(serie), class: 'card-link' %>
            <div class="card-body">
              <p class="card-text"><%= serie.title %></p>
              <p><%= serie.rating %> </p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <!-- </div> -->
</div>

app/views/series/new.html.erb
<div class="container my-5" style="width: 30%">
  <h1>New Title</h1>
  <%= simple_form_for @serie do |f| %>
    <%= f.input :title %>
    <%= f.submit class: 'btn btn-warning' %>
    <%= f.input :photo, as: :file %>
  <% end %>
</div>

app/views/series/show.html.erb
<div class="card-review-container">
  <div class="card-category-show card-left">
       <% if @serie.photo.attached? %>
          <%=  cl_image_tag @serie.photo.key, class: 'card-img', alt: "alttext" %>
        <% else %>
            <%= image_tag @serie.image, class: 'card-img', alt: "alttext" %>
        <% end %>
    <div class="card-body-show">
      <p class="card-text-show"><%= @serie.title %></p>
      <p>Rating : <%= @serie.rating %> </p>
        <%= link_to 'add review', new_series_review_path(@serie), class: 'card-link-show btn badge-warning'  %>
　 　     <%= link_to "delete", serie_path(@serie), class: 'card-link-show btn badge-warning', method: :delete  %>
    </div>
  </div>
    <%#= image_tag @serie.image, alt: "alttext" %>
  <div class="card-category-show card-rigth">
    <!--<p class="card-text"><%= @serie.title %></p>
    <p>Rating: <%= @serie.rating %> </p>-->
      <p class="card-review-title">
        <strong>Reviews:</strong>
      </p>
    <% if @serie.reviews.any? %>
      <!--<ul>-->
        <% @serie.reviews.each do |review| %>
          <div class="review-content">
          <q class="review-text"><%= review.content %></q>
            <%= link_to review_path(review), class: 'remove-link',  method: :delete, data: {confirm: "Delete review?"} do %>
             <i class="far fa-trash-alt icon"></i>
             <% end %>
          </div>
        <% end %>
     <!-- </ul>-->
    <% end %>
  </div>

</div>